export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS'
export const GET_GAMES_LOADING = 'GET_GAMES_LOADING'
export const GET_GAMES_FAILED = 'GET_GAMES_FAILED'

export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS'
export const GET_PLAYERS_LOADING = 'GET_PLAYERS_LOADING'
export const GET_PLAYERS_FAILED = 'GET_PLAYERS_FAILED'
